name: Deploy Go Echo App to EC2

on:
  push:
    branches:
      - main

env:
  GO_VERSION: '1.20'
  DEPLOY_PATH: /var/www/backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go environment
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        check-latest: true
        cache: 'gomod'

    - name: Verify Go version
      run: go version

    - name: Tidy Go modules
      run: go mod tidy

    - name: Build server binary
      run: |
        mkdir -p build
        go build -o build/server cmd/main.go

    - name: Build sync binary
      run: |
        mkdir -p build
        go build -o build/sync cmd/main.go

    - name: Prepare deployment package
      run: |
        echo "Creating deployment package..."
        tar -czf deploy.tar.gz build

    - name: Upload deployment package to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        source: "deploy.tar.gz"
        target: "${{ env.DEPLOY_PATH }}"

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script_stop: true
        envs: DEPLOY_PATH
        script: |
          # Ensure the deployment directory exists
          sudo mkdir -p $DEPLOY_PATH
          sudo chown -R $USER:$USER $DEPLOY_PATH

          # Stop existing PM2 processes
          echo "Stopping existing PM2 processes..."
          sudo pm2 stop go-echo-server || true
          sudo pm2 stop go-echo-sync || true

          # Backup current deployment
          if [ -d "$DEPLOY_PATH/build" ]; then
            echo "Creating backup..."
            cd $DEPLOY_PATH
            tar -czf backup-$(date +%Y%m%d_%H%M%S).tar.gz build
          fi

          # Clean current deployment
          echo "Cleaning current deployment..."
          rm -rf $DEPLOY_PATH/build

          # Extract new deployment
          echo "Extracting new deployment..."
          tar -xzf $DEPLOY_PATH/deploy.tar.gz -C $DEPLOY_PATH

          # Set executable permissions
          chmod +x $DEPLOY_PATH/build/server
          chmod +x $DEPLOY_PATH/build/sync

          # Remove the deployment package
          rm -f $DEPLOY_PATH/deploy.tar.gz

          # Ensure PM2 is installed
          if ! command -v pm2 &> /dev/null; then
            echo "Installing PM2..."
            sudo npm install -g pm2
          fi

          # Start processes with PM2
          echo "Starting processes with PM2..."
          sudo pm2 start $DEPLOY_PATH/build/server --name go-echo-server -- server
          sudo pm2 start $DEPLOY_PATH/build/sync --name go-echo-sync -- sync
          sudo pm2 save

          echo "Deployment completed successfully"
